title: Obsidian Notes
theme: jekyll-theme-minimal

collections:
  notes:
    output: true
    permalink: /notes/:path/

defaults:
  - scope:
      path: ""
      type: notes
    values:
      layout: note

exclude:
  - .obsidian
  - README.md