title: Obsidian Notes
theme: jekyll-theme-minimal

markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
  syntax_highlighter: rouge

collections:
  notes:
    output: true
    permalink: /notes/:path/

defaults:
  - scope:
      path: ""
      type: notes
    values:
      layout: note

exclude:
  - .obsidian
  - README.md