site_name: Machine Learning Notes
site_url: https://hanjie-jiang.github.io/ml-learning-notes/
docs_dir: _notes

extra_css:
  - assets/styles/layout.css

theme:
  name: material
  font:
    text: Inter
    code: JetBrains Mono
  features:
    # - navigation.instant
    - navigation.sections
    - navigation.top
    - content.code.copy
    - content.code.annotate
    - content.action.edit
    - content.tabs.link
    - toc.integrate
    - search.suggest
    - search.highlight

plugins:
  - search
  - roamlinks

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - pymdownx.betterem
  - pymdownx.tilde
  - pymdownx.tasklist
  - pymdownx.arithmatex
  - toc:
      permalink: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js

nav:
  - Home: index.md
  - Foundations:
      - ML Fundamentals: ml_fundamentals/ML_fundamentals.md
      - Probability & Markov:
          - Overview: probability_and_markov/Probability_and_Markov_Overview.md
          - Bayes’ Rule: probability_and_markov/probability_and_markov_sections/conditional_probability_and_bayes_rule.md
          - Naive Bayes: probability_and_markov/probability_and_markov_sections/naive_bayes_and_gaussian_naive_bayes.md
          - Joint & Marginal: probability_and_markov/probability_and_markov_sections/joint_and_marginal_distributions.md
  - Linear Algebra: Linear_Algebra_for_ML.md
  - Language Model: language_model/Ngram_Language_Modeling.md
  - Neural Networks:
      - Overview: Neural_Networks_and_Backprop.md
