site_name: Machine Learning Notes
site_url: https://hanjie-jiang.github.io/ml-learning-notes/
docs_dir: _notes

extra_css:
  - assets/styles/layout.css
  - assets/styles/hero.css

theme:
  name: material
  font:
    text: Inter
    code: JetBrains Mono
  features:
    # - navigation.instant
    - navigation.sections
    - navigation.top
    - content.code.copy
    - content.code.annotate
    - content.action.edit
    - content.tabs.link
    - toc.integrate
    - search.suggest
    - search.highlight

plugins:
  - search
  - roamlinks

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - pymdownx.betterem
  - pymdownx.tilde
  - pymdownx.tasklist
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/mathjax.js
  - javascripts/floating-nav.js
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js

nav:
  - Home: index.md
  - Engineering and Data Structure:
      - Overview: engineering_and_data_structure/Overview/Engineering_and_Data_Structure_Overview.md
      - Data Structures:
          - Arrays:
              - Arrays Overview: engineering_and_data_structure/Data_Structures/Arrays/Arrays_Overview.md
              - Dynamic Arrays: engineering_and_data_structure/Data_Structures/Arrays/Dynamic_Arrays.md
              - Array Problems: engineering_and_data_structure/Data_Structures/Arrays/Array_Problems.md
          - Hash Tables:
              - Hash Tables Overview: engineering_and_data_structure/Data_Structures/Hash_Tables/Hash_Tables_Overview.md
              - Hash Functions & Collisions: engineering_and_data_structure/Data_Structures/Hash_Tables/Hash_Functions_and_Collisions.md
              - Python Dictionaries: engineering_and_data_structure/Data_Structures/Hash_Tables/Python_Dictionaries.md
              - Python Dictionary Operations: engineering_and_data_structure/Data_Structures/Hash_Tables/Python_Dictionary_Operations.md
              - Python Sets: engineering_and_data_structure/Data_Structures/Hash_Tables/Python_Sets.md
              - Python Set Operations: engineering_and_data_structure/Data_Structures/Hash_Tables/Python_Set_Operations.md
              - String Operations: engineering_and_data_structure/Data_Structures/Hash_Tables/String_Operations.md
              - Hash Table Problems: engineering_and_data_structure/Data_Structures/Hash_Tables/Hash_Table_Problems.md
          - Recursion:
              - Recursion Fundamentals: engineering_and_data_structure/Data_Structures/Recursion/Recursion_Fundamentals.md
              - Recursive Algorithms: engineering_and_data_structure/Data_Structures/Recursion/Recursive_Algorithms.md
              - Recursion vs Iteration: engineering_and_data_structure/Data_Structures/Recursion/Recursion_vs_Iteration.md
              - Common Recursive Patterns: engineering_and_data_structure/Data_Structures/Recursion/Common_Recursive_Patterns.md
      - Algorithms:
          - Search Algorithms:
              - Search Overview: engineering_and_data_structure/Algorithms/Search_Algorithms/Search_Algorithms_Overview.md
              - Binary Search: engineering_and_data_structure/Algorithms/Search_Algorithms/Binary_Search_Fundamentals.md
              - Binary Search Variations: engineering_and_data_structure/Algorithms/Search_Algorithms/Binary_Search_Variations.md
              - Search Problems: engineering_and_data_structure/Algorithms/Search_Algorithms/Search_Problems.md
          - Sorting Algorithms:
              - Sorting Overview: engineering_and_data_structure/Algorithms/Sorting_Algorithms/Sorting_Algorithms_Overview.md
              - Sorting Problems: engineering_and_data_structure/Algorithms/Sorting_Algorithms/Sorting_Problems.md
      - Algorithmic Patterns:
          - Two Pointers:
              - Two Pointers Overview: engineering_and_data_structure/Algorithmic_Patterns/Two_Pointers/Two_Pointers_Overview.md
              - Opposite Direction: engineering_and_data_structure/Algorithmic_Patterns/Two_Pointers/Opposite_Direction_Pointers.md
              - Same Direction: engineering_and_data_structure/Algorithmic_Patterns/Two_Pointers/Same_Direction_Pointers.md
              - Two Pointers Problems: engineering_and_data_structure/Algorithmic_Patterns/Two_Pointers/Two_Pointers_Problems.md
          - Sliding Window:
              - Sliding Window Overview: engineering_and_data_structure/Algorithmic_Patterns/Sliding_Window/Sliding_Window_Overview.md
              - Fixed Size Window: engineering_and_data_structure/Algorithmic_Patterns/Sliding_Window/Fixed_Size_Window.md
              - Variable Size Window: engineering_and_data_structure/Algorithmic_Patterns/Sliding_Window/Variable_Size_Window.md
              - Sliding Window Problems: engineering_and_data_structure/Algorithmic_Patterns/Sliding_Window/Sliding_Window_Problems.md
      - Problem Solving:
          - Set & Dictionary Problems:
              - Array Intersection: engineering_and_data_structure/Problem_Solving/Set_Dictionary_Problems/Array_Intersection.md
              - Non-Repeating Elements: engineering_and_data_structure/Problem_Solving/Set_Dictionary_Problems/Non_Repeating_Elements.md
              - Unique Elements: engineering_and_data_structure/Problem_Solving/Set_Dictionary_Problems/Unique_Elements.md
              - Anagram Pairs: engineering_and_data_structure/Problem_Solving/Set_Dictionary_Problems/Anagram_Pairs.md
          - String Problems:
              - Unique Strings: engineering_and_data_structure/Problem_Solving/String_Problems/Unique_Strings.md
      - Resources:
          - Common Patterns: engineering_and_data_structure/Resources/Common_Patterns.md
          - Time Complexity Guide: engineering_and_data_structure/Resources/Time_Complexity_Guide.md
          - Interview Strategies: engineering_and_data_structure/Resources/Interview_Strategies.md
  - ML Foundations and Algorithms:
      - Probability & Markov:
          - Overview: probability_and_markov/Probability_and_Markov_Overview.md
          - Bayes’ Rule: probability_and_markov/probability_and_markov_sections/conditional_probability_and_bayes_rule.md
          - Naive Bayes: probability_and_markov/probability_and_markov_sections/naive_bayes_and_gaussian_naive_bayes.md
          - Joint & Marginal: probability_and_markov/probability_and_markov_sections/joint_and_marginal_distributions.md
      - Linear Algebra:
           - Linear Algebra for ML: calculus_and_linear_algebra/Linear_Algebra_for_ML.md
           - Calculus and Gradient Descent: calculus_and_linear_algebra/Calculus_and_Gradient_Descent.md
      - ML Fundamentals:
          - Overview: ml_fundamentals/ML_Fundamentals_Overview.md
          - Feature Engineering:
              - Data Types & Normalization: ml_fundamentals/feature_engineering/data_types_and_normalization.md
              - Categorical Encoding: ml_fundamentals/feature_engineering/categorical_encoding.md
              - Feature Crosses: ml_fundamentals/feature_engineering/feature_crosses.md
          - Model Evaluation:
              - Evaluation Methods: ml_fundamentals/model_evaluation/evaluation_methods.md
              - Metrics & Validation: ml_fundamentals/model_evaluation/metrics_and_validation.md
              - Hyperparameter Tuning: ml_fundamentals/model_evaluation/hyperparameter_tuning.md
          - Regularization:
              - Overfitting & Underfitting: ml_fundamentals/regularization/overfitting_underfitting.md
              - L1/L2 Regularization: ml_fundamentals/regularization/l1_l2_regularization.md
              - Early Stopping: ml_fundamentals/regularization/early_stopping.md
          - Classical Algorithms:
              - Linear Regression: ml_fundamentals/classical_algorithms/linear_regression.md
              - Logistic Regression: ml_fundamentals/classical_algorithms/logistic_regression.md
              - Decision Trees: ml_fundamentals/classical_algorithms/decision_trees.md
          - Unsupervised Learning:
              - K-Nearest Neighbors: ml_fundamentals/unsupervised_learning/k_nearest_neighbors.md
              - K-Means Clustering: ml_fundamentals/unsupervised_learning/k_means_clustering.md
  - Language Model: language_model/Ngram_Language_Modeling.md
  - Neural Networks:
      - Overview: neural_networks_and_deep_learning/Neural_Networks_and_Deep_Learning_Overview.md
      - Perceptron Algorithm: neural_networks_and_deep_learning/neural_networks_sections/Introduction_to_Perceptron_Algorithm.md
