site_name: Machine Learning Notes
site_url: https://hanjie-jiang.github.io/ml-learning-notes/
docs_dir: _notes

extra_css:
  - assets/styles/layout.css

theme:
  name: material
  font:
    text: Inter
    code: JetBrains Mono
  features:
    - navigation.instant
    - navigation.sections
    - navigation.top
    - content.code.copy
    - content.code.annotate
    - content.action.edit
    - content.tabs.link
    - toc.integrate
    - search.suggest
    - search.highlight

plugins:
  - search
  - roamlinks

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - pymdownx.betterem
  - pymdownx.tilde
  - pymdownx.tasklist
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js

nav:
  - Home: index.md
  - Foundations:
      - Probability & Markov:
          - Week 1 Overview: week1-2_probability_and_markov/Week1/README.md
          - Bayes’ Rule: week1-2_probability_and_markov/Week1/Week1P1-conditional_probability_and_bayes_rule.md
          - Naive Bayes: week1-2_probability_and_markov/Week1/Week1P2-naive_bayes_and_gaussian_naive_bayes.md
          - Joint & Marginal: week1-2_probability_and_markov/Week1/Week1P3-joint_and_marginal_distributions.md
          - ML Fundamentals: week1-2_probability_and_markov/Week1/Week1P4-ML_fundamentals.md
      - Linear Algebra: Week5_6_Linear_Algebra_for_ML.md
      - Information Theory: Entropy.md
  - Neural Networks:
      - Overview: Week8_9_Neural_Networks_and_Backprop.md
